@extends('layouts.app')
@section('title', 'Customers')
@section('content')
@php
    use App\Support\Format;
    $selected = $selectedCustomer;
    $stageClass = fn($s) => match($s) {'identify'=>'st-blue','approaching'=>'st-yellow','follow_up'=>'st-purple','won_closing'=>'st-green','lost'=>'st-red','maintaining'=>'st-green', default=>'st-gray'};
@endphp
<div class="sales-ui">
    <div class="sales-main-grid">
        <div>
            <div class="sales-page-head"><div><div class="small fw-bold text-primary mb-1">Customers &gt; Daftar Customer</div><h1 class="page-title mb-1">Customers</h1><div class="page-subtitle">Kelola informasi customer dan kontak utama.</div></div><a href="{{ route('sales.customers.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i>Tambah Customer</a></div>
            <div class="sales-grid-5" style="grid-template-columns:repeat(7,minmax(135px,1fr))"><div class="sales-stat"><div class="ico sblue"><i class="bi bi-people"></i></div><div><div class="label">Total Customers</div><div class="value">{{ $stats['total'] }}</div></div></div><div class="sales-stat"><div class="ico sblue"><i class="bi bi-compass"></i></div><div><div class="label">Identify</div><div class="value">{{ $stats['identify'] }}</div></div></div><div class="sales-stat"><div class="ico sorange"><i class="bi bi-person-lines-fill"></i></div><div><div class="label">Approaching</div><div class="value">{{ $stats['approaching'] }}</div></div></div><div class="sales-stat"><div class="ico spurple"><i class="bi bi-chat-left-dots"></i></div><div><div class="label">Follow Up</div><div class="value">{{ $stats['follow_up'] }}</div></div></div><div class="sales-stat"><div class="ico sgreen"><i class="bi bi-person-check"></i></div><div><div class="label">Won / Closing</div><div class="value">{{ $stats['won'] }}</div></div></div><div class="sales-stat"><div class="ico sred"><i class="bi bi-x-circle"></i></div><div><div class="label">Lost</div><div class="value">{{ $stats['lost'] }}</div></div></div><div class="sales-stat"><div class="ico steal"><i class="bi bi-arrow-repeat"></i></div><div><div class="label">Maintaining</div><div class="value">{{ $stats['maintaining'] }}</div></div></div></div>
            <div class="card-r p-0 overflow-hidden"><form class="sales-filter-row p-3 pb-0" method="GET" style="grid-template-columns:minmax(260px,1fr) 160px 160px 160px auto auto"><div class="sales-search"><i class="bi bi-search"></i><input type="text" name="q" value="{{ request('q') }}" class="form-control" placeholder="Cari customer..."></div><select name="status" class="form-select"><option value="">Semua Status</option>@foreach(\App\Models\Customer::stages() as $k=>$v)<option value="{{ $k }}" @selected(request('status')==$k)>{{ $v }}</option>@endforeach</select><select name="category" class="form-select"><option value="">Semua Kategori</option><option>Pendidikan</option><option>Industri</option><option>Kesehatan</option></select><select class="form-select"><option>Semua Sales</option></select><button class="btn btn-soft"><i class="bi bi-funnel me-1"></i>Filter Lainnya</button><button type="button" class="btn btn-soft"><i class="bi bi-file-earmark"></i></button></form><div class="table-wrap"><table class="sales-table"><thead><tr><th>No.</th><th>Nama Customer</th><th>PIC Utama</th><th>Email</th><th>No. Telepon</th><th>Kategori</th><th>Status</th><th>Sales</th><th>Aksi</th></tr></thead><tbody>@forelse($customers as $cust)<tr class="{{ $selected && $selected->id===$cust->id?'selected':'' }}"><td>{{ $customers->firstItem()+$loop->index }}</td><td><a href="{{ route('sales.customers.show',$cust) }}" class="fw-bold">{{ $cust->name }}</a></td><td>{{ $cust->primaryPic?->name ?? $cust->pic_name ?? '-' }}</td><td>{{ $cust->email ?: '-' }}</td><td>{{ $cust->phone ?: '-' }}</td><td>{{ $cust->category ?: '-' }}</td><td><span class="status-soft {{ $stageClass($cust->pipeline_stage) }}">{{ \App\Models\Customer::stages()[$cust->pipeline_stage] ?? $cust->pipeline_stage }}</span></td><td>{{ $cust->sales?->name ?? '-' }}</td><td><div class="dropdown"><button class="btn btn-sm btn-soft" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button><div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="{{ route('sales.customers.show',$cust) }}">Lihat Detail</a><a class="dropdown-item" href="{{ route('sales.customers.edit',$cust) }}">Edit Customer</a></div></div></td></tr>@empty<tr><td colspan="9"><x-empty text="Belum ada customer." /></td></tr>@endforelse</tbody></table></div><div class="p-3 d-flex justify-content-between"><span class="small text-muted-2">Menampilkan {{ $customers->firstItem() ?? 0 }} - {{ $customers->lastItem() ?? 0 }} dari {{ $customers->total() }} data</span>{{ $customers->links() }}</div></div>
        </div>
        <aside class="sales-detail">
            @if($selected)
                <div class="sales-detail-head"><div class="text-center w-100"><div class="logo-avatar mx-auto mb-2" style="width:64px;height:64px"><i class="bi bi-building fs-3"></i></div><h4 class="fw-black mb-1">{{ $selected->name }}</h4><span class="status-soft {{ $stageClass($selected->pipeline_stage) }}">{{ \App\Models\Customer::stages()[$selected->pipeline_stage] ?? $selected->pipeline_stage }}</span><a href="{{ route('sales.customers.edit',$selected) }}" class="btn btn-soft w-100 mt-3"><i class="bi bi-pencil me-1"></i>Edit Customer</a></div></div>
                <div class="sales-detail-body"><div class="info-card mb-3"><h6>Informasi Utama</h6><div class="kv"><div class="k">PIC Utama</div><div class="v">{{ $selected->primaryPic?->name ?? '-' }}</div></div><div class="kv"><div class="k">Email</div><div class="v">{{ $selected->email ?: '-' }}</div></div><div class="kv"><div class="k">No. Telepon</div><div class="v">{{ $selected->phone ?: '-' }}</div></div><div class="kv"><div class="k">Alamat</div><div class="v">{{ $selected->address ?: '-' }}</div></div></div><div class="info-card mb-3"><h6>Status Customer</h6><div class="sales-chip-row">@foreach(\App\Models\Customer::stages() as $k=>$v)<span class="status-soft {{ $stageClass($k) }} {{ $selected->pipeline_stage===$k?'':'opacity-50' }}">{{ $v }}</span>@endforeach</div><div class="kv mt-3"><div class="k">Probabilitas</div><div class="v">{{ $selected->probability }}%<div class="sales-progress mt-1"><span style="width:{{ $selected->probability }}%"></span></div></div></div></div><div class="info-card"><h6>Ringkasan Aktivitas</h6><div class="kv"><div class="k">Total Penawaran</div><div class="v">{{ $selected->quotations_count ?? $selected->quotations()->count() }}</div></div><div class="kv"><div class="k">Total Project</div><div class="v">{{ $selected->projects()->count() }}</div></div><div class="kv"><div class="k">Total Nilai Penawaran</div><div class="v">{{ Format::rupiahShort($selected->quotations()->sum('grand_total')) }}</div></div><a href="{{ route('sales.customers.show',$selected) }}" class="btn btn-soft w-100 mt-3">Lihat Semua Aktivitas <i class="bi bi-arrow-right"></i></a></div></div>
            @else
                <div class="sales-detail-body"><x-empty text="Belum ada customer." /></div>
            @endif
        </aside>
    </div>
</div>
@endsection
